#!/system/bin/sh

dnscrypt-proxy -pidfile /data/local/tmp/dnscrypt-proxy.pid -config /system/etc/dnscrypt-proxy/dnscrypt-proxy.toml &
sleep 5
iptables -t nat -A OUTPUT -p udp --dport 53 -j DNAT --to-destination 127.0.0.1 && \
iptables -t nat -A OUTPUT -p tcp --dport 53 -j DNAT --to-destination 127.0.0.1
echo "Done!"
