#!/system/bin/sh

if [ "x${1}" = "xenable" -o "x${1}" = "xENABLE" ]; then
        echo "Enabling dnscrypt-proxy..."
        iptables -t nat -D OUTPUT -p udp --dport 53 -j DNAT --to-destination 127.0.0.1
        iptables -t nat -D OUTPUT -p tcp --dport 53 -j DNAT --to-destination 127.0.0.1
        kill $(cat /data/local/tmp/dnscrypt-proxy.pid)
        MODDIR=/magisk/dnscrypt-proxy
        SCRIPTLIST=`find $MODDIR/script -maxdepth 1 -type f ! -name "99dnscrypt" 2>/dev/null | sort -d`
        if [ ! -z "$SCRIPTLIST" ]; then
          for ITEM in $SCRIPTLIST; do
            echo "Running script ${ITEM}..."
            chmod 755 "$ITEM"
            /system/bin/sh "$ITEM"
          done
        else
          chmod 755 $MODDIR/script/99dnscrypt
          echo "Running script 99dnscrypt..."
          /system/bin/sh "$MODDIR/script/99dnscrypt"
        fi
        # echo "Setting DNS as 127.0.0.1"
        # setprop 'net.dns1' '127.0.0.1﻿'
        echo "Done"
        exit
elif [ "x${1}" = "xdisable" -o "x${1}" = "xDISABLE" ]; then
        echo "Disabling dnscrypt-proxy..."
        iptables -t nat -D OUTPUT -p udp --dport 53 -j DNAT --to-destination 127.0.0.1
        iptables -t nat -D OUTPUT -p tcp --dport 53 -j DNAT --to-destination 127.0.0.1
        kill $(cat /data/local/tmp/dnscrypt-proxy.pid)
        echo "Done"
        exit
else
        echo "This script allows you to enable or"
        echo "disable dnscrypt-proxy."
        echo
        echo "Usage:"
        echo "enable    -    Enable dnscrypt"
        echo "disable   -    Disable dnscrypt"
        echo
fi
